---
dist: xenial
sudo: required
language: ruby
rvm:
  - 2.6

addons:
  apt:
    sources:
      - sourceline: 'deb https://packages.chef.io/repos/apt/current xenial main'
        key_url: 'https://packages.chef.io/chef.asc'
    packages:
      - chefdk

script:
  - make lint
